apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/YingCi56/ArgoApp
  password: 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
  username: not-used
