apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webserver-argo
        image: yingci56/dockerhub:argoapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"